const CACHE='vocab-curve-v16-4';
const ASSETS=["./", "./index.html", "./manifest.webmanifest", "./v16.css", "./v16-rules.js", "./v16-learning.js", "./v16-transfer.js", "./v16-runtime.js", "./icons/icon-192.png", "./icons/icon-512.png", "./assets/badge-common.png", "./assets/badge-epic.png", "./assets/badge-legendary.png", "./assets/badge-mythic.png", "./assets/badge-rare.png", "./assets/badge-uncommon.png", "./assets/rank-A.png", "./assets/rank-Aplus.png", "./assets/rank-B.png", "./assets/rank-Bplus.png", "./assets/rank-C.png", "./assets/rank-Cplus.png", "./assets/rank-D.png", "./assets/rank-S.png", "./assets/rank-s-demon.png", "./assets/rank-s-diamond.png", "./assets/rank-s-gold.png", "./assets/rank-s-platinum.png", "./assets/rank-s-silver.png", "./assets/tab-account.png", "./assets/tab-achievements.png", "./assets/tab-books.png", "./assets/tab-import.png", "./assets/tab-more.png", "./assets/tab-planner.png", "./assets/tab-ranked.png", "./assets/tab-save.png", "./assets/tab-settings.png", "./assets/tab-stats.png", "./assets/tab-study.png", "./assets/characters/nova.png", "./assets/characters/mender.png", "./assets/characters/volt.png", "./assets/characters/lumen.png", "./assets/characters/echo.png", "./assets/characters/root.png", "./assets/characters/ace.png", "./assets/characters/mirage.png", "./assets/characters/aegis.png", "./assets/characters/revenant.png", "./assets/glory/spark.png", "./assets/glory/flame.png", "./assets/glory/blaze.png", "./assets/glory/inferno.png", "./assets/glory/sun.png", "./assets/glory/white-dwarf.png", "./assets/glory/pulsar.png", "./assets/glory/black-hole.png"];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim()).then(()=>self.clients.matchAll().then(clients=>clients.forEach(client=>client.postMessage('V16_READY'))))));
self.addEventListener('message',event=>{if(event.data==='SKIP_WAITING')self.skipWaiting();});
self.addEventListener('fetch',event=>{
  if(event.request.method!=='GET')return;
  const request=event.request;
  if(request.mode==='navigate'){event.respondWith(fetch(request).then(response=>{const copy=response.clone();caches.open(CACHE).then(cache=>cache.put('./index.html',copy));return response;}).catch(()=>caches.match('./index.html')));return;}
  event.respondWith(caches.match(request).then(cached=>cached||fetch(request).then(response=>{const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(request,copy));return response;})));
});
